In [6]:
import requests

In [9]:
URL ='https://stephen-king-api.onrender.com/api/books'

res = requests.get(URL)

In [10]:
json_data = res.json()

In [13]:
import pandas as pd

df =pd.json_normalize(json_data['data'])
df =df[['id','Title','Year','ISBN']]

In [14]:
df

    id          Title  Year               ISBN
0    1         Carrie  1974  978-0-385-08695-0
1    2    Salem's Lot  1975  978-0-385-00751-1
2    3    The Shining  1977  978-0-385-12167-5
3    4           Rage  1977  978-0-451-07645-8
4    5      The Stand  1978  978-0-385-12168-2
..  ..            ...   ...                ...
58  59   The Outsider  2018  978-1-50118-098-9
59  60      Elevation  2018  978-1-98210-231-9
60  61  The Institute  2019  978-1-98211-056-7
61  62          Later  2021  978-1-78909-649-1
62  63  Billy Summers  2021  978-1-982-17361-6

[63 rows x 4 columns]

In [2]:
# Web scraping
import requests

URL = 'https://www.scrapethissite.com/pages/simple/'
res = requests.get(URL)

In [3]:
if res.status_code == 200:
    print(res.status_code)

200

In [4]:
with open("scraped_data/data1.html", "w", encoding="utf-8") as f:
    f.write(res.text)

In [5]:
pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in c:\users\vaibh\anaconda3\lib\site-packages (4.13.5)
Requirement already satisfied: soupsieve>1.2 in c:\users\vaibh\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\vaibh\anaconda3\lib\site-packages (from beautifulsoup4) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [10]:
from bs4 import BeautifulSoup

with open("scraped_data/data1.html", "r") as f:
    html_content = f.read()

soup = BeautifulSoup(html_content,"lxml")

In [45]:
#soup
#soup.find('h1')
#soup.h1
all_h3 = soup.find_all('h3')
#print(all_h3)
type(all_h3)

for h3 in all_h3:
    #print(h3.get_text())
    name = h3.get_text(strip = True)
    #print(h3.find_parent('div'))
    #print(h3.find_parent('div')['class'])
    #print(h3.find_next('div'))
    #print(h3.find_next('div').select('span.country-population')[0].get_text(strip =True))
    population = h3.find_next('div').select_one('span.country-population').get_text(strip =True)
    print(population)
    print(h3.attrs)
    #print(h3.parent)
    #print(h3.child)

84000
{'class': ['country-name']}
4975593
{'class': ['country-name']}
29121286
{'class': ['country-name']}
86754
{'class': ['country-name']}
13254
{'class': ['country-name']}
2986952
{'class': ['country-name']}
2968000
{'class': ['country-name']}
13068161
{'class': ['country-name']}
0
{'class': ['country-name']}
41343201
{'class': ['country-name']}
57881
{'class': ['country-name']}
8205000
{'class': ['country-name']}
21515754
{'class': ['country-name']}
71566
{'class': ['country-name']}
26711
{'class': ['country-name']}
8303512
{'class': ['country-name']}
4590000
{'class': ['country-name']}
285653
{'class': ['country-name']}
156118464
{'class': ['country-name']}
10403000
{'class': ['country-name']}
16241811
{'class': ['country-name']}
7148785
{'class': ['country-name']}
738004
{'class': ['country-name']}
9863117
{'class': ['country-name']}
9056010
{'class': ['country-name']}
8450
{'class': ['country-name']}
65365
{'class': ['country-name']}
395027
{'class': ['country-name']}
9947418
{'class': ['country-name']}
18012
{'class': ['country-name']}
201103330
{'class': ['country-name']}
301790
{'class': ['country-name']}
699847
{'class': ['country-name']}
0
{'class': ['country-name']}
2029307
{'class': ['country-name']}
9685000
{'class': ['country-name']}
314522
{'class': ['country-name']}
33679000
{'class': ['country-name']}
628
{'class': ['country-name']}
70916439
{'class': ['country-name']}
4844927
{'class': ['country-name']}
3039126
{'class': ['country-name']}
7581000
{'class': ['country-name']}
21058798
{'class': ['country-name']}
21388
{'class': ['country-name']}
16746491
{'class': ['country-name']}
19294149
{'class': ['country-name']}
1330044000
{'class': ['country-name']}
47790000
{'class': ['country-name']}
4516220
{'class': ['country-name']}
11423000
{'class': ['country-name']}
508659
{'class': ['country-name']}
141766
{'class': ['country-name']}
1500
{'class': ['country-name']}
1102677
{'class': ['country-name']}
10476000
{'class': ['country-name']}
81802257
{'class': ['country-name']}
740528
{'class': ['country-name']}
5484000
{'class': ['country-name']}
72813
{'class': ['country-name']}
9823821
{'class': ['country-name']}
34586184
{'class': ['country-name']}
14790608
{'class': ['country-name']}
1291170
{'class': ['country-name']}
80471869
{'class': ['country-name']}
273008
{'class': ['country-name']}
5792984
{'class': ['country-name']}
46505963
{'class': ['country-name']}
88013491
{'class': ['country-name']}
5244000
{'class': ['country-name']}
875983
{'class': ['country-name']}
2638
{'class': ['country-name']}
107708
{'class': ['country-name']}
48228
{'class': ['country-name']}
64768389
{'class': ['country-name']}
1545255
{'class': ['country-name']}
62348447
{'class': ['country-name']}
107818
{'class': ['country-name']}
4630000
{'class': ['country-name']}
195506
{'class': ['country-name']}
65228
{'class': ['country-name']}
24339838
{'class': ['country-name']}
27884
{'class': ['country-name']}
56375
{'class': ['country-name']}
1593256
{'class': ['country-name']}
10324025
{'class': ['country-name']}
443000
{'class': ['country-name']}
1014999
{'class': ['country-name']}
11000000
{'class': ['country-name']}
30
{'class': ['country-name']}
13550440
{'class': ['country-name']}
159358
{'class': ['country-name']}
1565126
{'class': ['country-name']}
748486
{'class': ['country-name']}
6898686
{'class': ['country-name']}
0
{'class': ['country-name']}
7989415
{'class': ['country-name']}
4491000
{'class': ['country-name']}
9648924
{'class': ['country-name']}
9982000
{'class': ['country-name']}
242968342
{'class': ['country-name']}
4622917
{'class': ['country-name']}
7353985
{'class': ['country-name']}
75049
{'class': ['country-name']}
1173108018
{'class': ['country-name']}
4000
{'class': ['country-name']}
29671605
{'class': ['country-name']}
76923300
{'class': ['country-name']}
308910
{'class': ['country-name']}
60340328
{'class': ['country-name']}
90812
{'class': ['country-name']}
2847232
{'class': ['country-name']}
6407085
{'class': ['country-name']}
127288000
{'class': ['country-name']}
40046566
{'class': ['country-name']}
5776500
{'class': ['country-name']}
14453680
{'class': ['country-name']}
92533
{'class': ['country-name']}
773407
{'class': ['country-name']}
51134
{'class': ['country-name']}
22912177
{'class': ['country-name']}
48422644
{'class': ['country-name']}
2789132
{'class': ['country-name']}
44270
{'class': ['country-name']}
15340000
{'class': ['country-name']}
6368162
{'class': ['country-name']}
4125247
{'class': ['country-name']}
160922
{'class': ['country-name']}
35000
{'class': ['country-name']}
21513990
{'class': ['country-name']}
3685076
{'class': ['country-name']}
1919552
{'class': ['country-name']}
2944459
{'class': ['country-name']}
497538
{'class': ['country-name']}
2217969
{'class': ['country-name']}
6461454
{'class': ['country-name']}
31627428
{'class': ['country-name']}
32965
{'class': ['country-name']}
4324000
{'class': ['country-name']}
666730
{'class': ['country-name']}
35925
{'class': ['country-name']}
21281844
{'class': ['country-name']}
65859
{'class': ['country-name']}
2062294
{'class': ['country-name']}
13796354
{'class': ['country-name']}
53414374
{'class': ['country-name']}
3086918
{'class': ['country-name']}
449198
{'class': ['country-name']}
53883
{'class': ['country-name']}
432900
{'class': ['country-name']}
3205060
{'class': ['country-name']}
9341
{'class': ['country-name']}
403000
{'class': ['country-name']}
1294104
{'class': ['country-name']}
395650
{'class': ['country-name']}
15447500
{'class': ['country-name']}
112468855
{'class': ['country-name']}
28274729
{'class': ['country-name']}
22061451
{'class': ['country-name']}
2128471
{'class': ['country-name']}
216494
{'class': ['country-name']}
15878271
{'class': ['country-name']}
1828
{'class': ['country-name']}
154000000
{'class': ['country-name']}
5995928
{'class': ['country-name']}
16645000
{'class': ['country-name']}
5009150
{'class': ['country-name']}
28951852
{'class': ['country-name']}
10065
{'class': ['country-name']}
2166
{'class': ['country-name']}
4252277
{'class': ['country-name']}
2967717
{'class': ['country-name']}
3410676
{'class': ['country-name']}
29907003
{'class': ['country-name']}
270485
{'class': ['country-name']}
6064515
{'class': ['country-name']}
99900177
{'class': ['country-name']}
184404791
{'class': ['country-name']}
38500000
{'class': ['country-name']}
7012
{'class': ['country-name']}
46
{'class': ['country-name']}
3916632
{'class': ['country-name']}
3800000
{'class': ['country-name']}
10676000
{'class': ['country-name']}
19907
{'class': ['country-name']}
6375830
{'class': ['country-name']}
840926
{'class': ['country-name']}
776948
{'class': ['country-name']}
21959278
{'class': ['country-name']}
7344847
{'class': ['country-name']}
140702000
{'class': ['country-name']}
11055976
{'class': ['country-name']}
25731776
{'class': ['country-name']}
559198
{'class': ['country-name']}
88340
{'class': ['country-name']}
35000000
{'class': ['country-name']}
9828655
{'class': ['country-name']}
4701069
{'class': ['country-name']}
7460
{'class': ['country-name']}
2007000
{'class': ['country-name']}
2550
{'class': ['country-name']}
5455000
{'class': ['country-name']}
5245695
{'class': ['country-name']}
31477
{'class': ['country-name']}
12323252
{'class': ['country-name']}
10112453
{'class': ['country-name']}
492829
{'class': ['country-name']}
8260490
{'class': ['country-name']}
175808
{'class': ['country-name']}
6052064
{'class': ['country-name']}
37429
{'class': ['country-name']}
22198110
{'class': ['country-name']}
1354051
{'class': ['country-name']}
20556
{'class': ['country-name']}
10543464
{'class': ['country-name']}
140
{'class': ['country-name']}
6587239
{'class': ['country-name']}
67089500
{'class': ['country-name']}
7487489
{'class': ['country-name']}
1466
{'class': ['country-name']}
1154625
{'class': ['country-name']}
4940916
{'class': ['country-name']}
10589025
{'class': ['country-name']}
122580
{'class': ['country-name']}
77804122
{'class': ['country-name']}
1228691
{'class': ['country-name']}
10472
{'class': ['country-name']}
22894384
{'class': ['country-name']}
41892895
{'class': ['country-name']}
45415596
{'class': ['country-name']}
33398682
{'class': ['country-name']}
0
{'class': ['country-name']}
310232863
{'class': ['country-name']}
3477000
{'class': ['country-name']}
27865738
{'class': ['country-name']}
921
{'class': ['country-name']}
104217
{'class': ['country-name']}
27223228
{'class': ['country-name']}
21730
{'class': ['country-name']}
108708
{'class': ['country-name']}
89571130
{'class': ['country-name']}
221552
{'class': ['country-name']}
16025
{'class': ['country-name']}
192001
{'class': ['country-name']}
1800000
{'class': ['country-name']}
23495361
{'class': ['country-name']}
159042
{'class': ['country-name']}
49000000
{'class': ['country-name']}
13460305
{'class': ['country-name']}
11651858
{'class': ['country-name']}

In [56]:

all_h3 = soup.find_all('h3')
all_countries =[]
for h3 in all_h3:
    
    name = h3.get_text(strip = True)

    population = h3.find_next('div').select_one('span.country-population').get_text(strip = True)

    all_countries.append([name,population])

In [57]:
all_countries

[['Andorra', '84000'],
 ['United Arab Emirates', '4975593'],
 ['Afghanistan', '29121286'],
 ['Antigua and Barbuda', '86754'],
 ['Anguilla', '13254'],
 ['Albania', '2986952'],
 ['Armenia', '2968000'],
 ['Angola', '13068161'],
 ['Antarctica', '0'],
 ['Argentina', '41343201'],
 ['American Samoa', '57881'],
 ['Austria', '8205000'],
 ['Australia', '21515754'],
 ['Aruba', '71566'],
 ['Ã…land', '26711'],
 ['Azerbaijan', '8303512'],
 ['Bosnia and Herzegovina', '4590000'],
 ['Barbados', '285653'],
 ['Bangladesh', '156118464'],
 ['Belgium', '10403000'],
 ['Burkina Faso', '16241811'],
 ['Bulgaria', '7148785'],
 ['Bahrain', '738004'],
 ['Burundi', '9863117'],
 ['Benin', '9056010'],
 ['Saint BarthÃ©lemy', '8450'],
 ['Bermuda', '65365'],
 ['Brunei', '395027'],
 ['Bolivia', '9947418'],
 ['Bonaire', '18012'],
 ['Brazil', '201103330'],
 ['Bahamas', '301790'],
 ['Bhutan', '699847'],
 ['Bouvet Island', '0'],
 ['Botswana', '2029307'],
 ['Belarus', '9685000'],
 ['Belize', '314522'],
 ['Canada', '33679000'],
 ['Cocos [Keeling] Islands', '628'],
 ['Democratic Republic of the Congo', '70916439'],
 ['Central African Republic', '4844927'],
 ['Republic of the Congo', '3039126'],
 ['Switzerland', '7581000'],
 ['Ivory Coast', '21058798'],
 ['Cook Islands', '21388'],
 ['Chile', '16746491'],
 ['Cameroon', '19294149'],
 ['China', '1330044000'],
 ['Colombia', '47790000'],
 ['Costa Rica', '4516220'],
 ['Cuba', '11423000'],
 ['Cape Verde', '508659'],
 ['Curacao', '141766'],
 ['Christmas Island', '1500'],
 ['Cyprus', '1102677'],
 ['Czech Republic', '10476000'],
 ['Germany', '81802257'],
 ['Djibouti', '740528'],
 ['Denmark', '5484000'],
 ['Dominica', '72813'],
 ['Dominican Republic', '9823821'],
 ['Algeria', '34586184'],
 ['Ecuador', '14790608'],
 ['Estonia', '1291170'],
 ['Egypt', '80471869'],
 ['Western Sahara', '273008'],
 ['Eritrea', '5792984'],
 ['Spain', '46505963'],
 ['Ethiopia', '88013491'],
 ['Finland', '5244000'],
 ['Fiji', '875983'],
 ['Falkland Islands', '2638'],
 ['Micronesia', '107708'],
 ['Faroe Islands', '48228'],
 ['France', '64768389'],
 ['Gabon', '1545255'],
 ['United Kingdom', '62348447'],
 ['Grenada', '107818'],
 ['Georgia', '4630000'],
 ['French Guiana', '195506'],
 ['Guernsey', '65228'],
 ['Ghana', '24339838'],
 ['Gibraltar', '27884'],
 ['Greenland', '56375'],
 ['Gambia', '1593256'],
 ['Guinea', '10324025'],
 ['Guadeloupe', '443000'],
 ['Equatorial Guinea', '1014999'],
 ['Greece', '11000000'],
 ['South Georgia and the South Sandwich Islands', '30'],
 ['Guatemala', '13550440'],
 ['Guam', '159358'],
 ['Guinea-Bissau', '1565126'],
 ['Guyana', '748486'],
 ['Hong Kong', '6898686'],
 ['Heard Island and McDonald Islands', '0'],
 ['Honduras', '7989415'],
 ['Croatia', '4491000'],
 ['Haiti', '9648924'],
 ['Hungary', '9982000'],
 ['Indonesia', '242968342'],
 ['Ireland', '4622917'],
 ['Israel', '7353985'],
 ['Isle of Man', '75049'],
 ['India', '1173108018'],
 ['British Indian Ocean Territory', '4000'],
 ['Iraq', '29671605'],
 ['Iran', '76923300'],
 ['Iceland', '308910'],
 ['Italy', '60340328'],
 ['Jersey', '90812'],
 ['Jamaica', '2847232'],
 ['Jordan', '6407085'],
 ['Japan', '127288000'],
 ['Kenya', '40046566'],
 ['Kyrgyzstan', '5776500'],
 ['Cambodia', '14453680'],
 ['Kiribati', '92533'],
 ['Comoros', '773407'],
 ['Saint Kitts and Nevis', '51134'],
 ['North Korea', '22912177'],
 ['South Korea', '48422644'],
 ['Kuwait', '2789132'],
 ['Cayman Islands', '44270'],
 ['Kazakhstan', '15340000'],
 ['Laos', '6368162'],
 ['Lebanon', '4125247'],
 ['Saint Lucia', '160922'],
 ['Liechtenstein', '35000'],
 ['Sri Lanka', '21513990'],
 ['Liberia', '3685076'],
 ['Lesotho', '1919552'],
 ['Lithuania', '2944459'],
 ['Luxembourg', '497538'],
 ['Latvia', '2217969'],
 ['Libya', '6461454'],
 ['Morocco', '31627428'],
 ['Monaco', '32965'],
 ['Moldova', '4324000'],
 ['Montenegro', '666730'],
 ['Saint Martin', '35925'],
 ['Madagascar', '21281844'],
 ['Marshall Islands', '65859'],
 ['Macedonia', '2062294'],
 ['Mali', '13796354'],
 ['Myanmar [Burma]', '53414374'],
 ['Mongolia', '3086918'],
 ['Macao', '449198'],
 ['Northern Mariana Islands', '53883'],
 ['Martinique', '432900'],
 ['Mauritania', '3205060'],
 ['Montserrat', '9341'],
 ['Malta', '403000'],
 ['Mauritius', '1294104'],
 ['Maldives', '395650'],
 ['Malawi', '15447500'],
 ['Mexico', '112468855'],
 ['Malaysia', '28274729'],
 ['Mozambique', '22061451'],
 ['Namibia', '2128471'],
 ['New Caledonia', '216494'],
 ['Niger', '15878271'],
 ['Norfolk Island', '1828'],
 ['Nigeria', '154000000'],
 ['Nicaragua', '5995928'],
 ['Netherlands', '16645000'],
 ['Norway', '5009150'],
 ['Nepal', '28951852'],
 ['Nauru', '10065'],
 ['Niue', '2166'],
 ['New Zealand', '4252277'],
 ['Oman', '2967717'],
 ['Panama', '3410676'],
 ['Peru', '29907003'],
 ['French Polynesia', '270485'],
 ['Papua New Guinea', '6064515'],
 ['Philippines', '99900177'],
 ['Pakistan', '184404791'],
 ['Poland', '38500000'],
 ['Saint Pierre and Miquelon', '7012'],
 ['Pitcairn Islands', '46'],
 ['Puerto Rico', '3916632'],
 ['Palestine', '3800000'],
 ['Portugal', '10676000'],
 ['Palau', '19907'],
 ['Paraguay', '6375830'],
 ['Qatar', '840926'],
 ['RÃ©union', '776948'],
 ['Romania', '21959278'],
 ['Serbia', '7344847'],
 ['Russia', '140702000'],
 ['Rwanda', '11055976'],
 ['Saudi Arabia', '25731776'],
 ['Solomon Islands', '559198'],
 ['Seychelles', '88340'],
 ['Sudan', '35000000'],
 ['Sweden', '9828655'],
 ['Singapore', '4701069'],
 ['Saint Helena', '7460'],
 ['Slovenia', '2007000'],
 ['Svalbard and Jan Mayen', '2550'],
 ['Slovakia', '5455000'],
 ['Sierra Leone', '5245695'],
 ['San Marino', '31477'],
 ['Senegal', '12323252'],
 ['Somalia', '10112453'],
 ['Suriname', '492829'],
 ['South Sudan', '8260490'],
 ['SÃ£o TomÃ© and PrÃ\xadncipe', '175808'],
 ['El Salvador', '6052064'],
 ['Sint Maarten', '37429'],
 ['Syria', '22198110'],
 ['Swaziland', '1354051'],
 ['Turks and Caicos Islands', '20556'],
 ['Chad', '10543464'],
 ['French Southern Territories', '140'],
 ['Togo', '6587239'],
 ['Thailand', '67089500'],
 ['Tajikistan', '7487489'],
 ['Tokelau', '1466'],
 ['East Timor', '1154625'],
 ['Turkmenistan', '4940916'],
 ['Tunisia', '10589025'],
 ['Tonga', '122580'],
 ['Turkey', '77804122'],
 ['Trinidad and Tobago', '1228691'],
 ['Tuvalu', '10472'],
 ['Taiwan', '22894384'],
 ['Tanzania', '41892895'],
 ['Ukraine', '45415596'],
 ['Uganda', '33398682'],
 ['U.S. Minor Outlying Islands', '0'],
 ['United States', '310232863'],
 ['Uruguay', '3477000'],
 ['Uzbekistan', '27865738'],
 ['Vatican City', '921'],
 ['Saint Vincent and the Grenadines', '104217'],
 ['Venezuela', '27223228'],
 ['British Virgin Islands', '21730'],
 ['U.S. Virgin Islands', '108708'],
 ['Vietnam', '89571130'],
 ['Vanuatu', '221552'],
 ['Wallis and Futuna', '16025'],
 ['Samoa', '192001'],
 ['Kosovo', '1800000'],
 ['Yemen', '23495361'],
 ['Mayotte', '159042'],
 ['South Africa', '49000000'],
 ['Zambia', '13460305'],
 ['Zimbabwe', '11651858']]

In [60]:
import pandas as pd
df =pd.DataFrame(all_countries,columns =['Name','Population'])
df

                     Name Population
0                 Andorra      84000
1    United Arab Emirates    4975593
2             Afghanistan   29121286
3     Antigua and Barbuda      86754
4                Anguilla      13254
..                    ...        ...
245                 Yemen   23495361
246               Mayotte     159042
247          South Africa   49000000
248                Zambia   13460305
249              Zimbabwe   11651858

[250 rows x 2 columns]

In [62]:
df.to_csv("cleaned_data/data.csv",index =False)